# Generated by Django 4.2.6 on 2023-12-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0007_alter_seccion_profesor'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='asistencia',
            constraint=models.UniqueConstraint(fields=('clase', 'alumno', 'fecha'), name='unique_asistencia_combination'),
        ),
    ]
